
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSessionProvider from "@/components/ClientSessionProvider";
import { ScheduleProvider } from "@/components/schedule/ScheduleContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientSessionProvider>
          <ScheduleProvider>
            {children}
          </ScheduleProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}